{
  pkgs,
  lib,
  ...
}:
lib.buildGradleApkGradle2Nix {
  pname = "fossify-phone";
  version = "1.11.1";

  src = pkgs.fetchFromGitHub {
    owner = "FossifyOrg";
    repo = "Phone";
    tag = "1.11.1";
    hash = "sha256-KSjlnz7quQgI7ymyst2uDQQ9WwSRyohJs8SlWIUrm+4=";
  };

  androidSdkPackages =
    sdkPkgs: with sdkPkgs; [
      build-tools-35-0-0
      build-tools-36-0-0
      cmdline-tools-latest
      platform-tools
      platforms-android-36
    ];

  gradleTask = "assembleFossRelease";
  # per-app lock generated by the gradle2nix CLI (see docs/adding-new-app)
  lockFile = ./gradle.lock;
  apkPath = "app/build/outputs/apk/foss/release/phone-22-foss-release-unsigned.apk";

  meta = {
    description = "Phone dialer and call log app, without ads";
    homepage = "https://fossify.org";
    license = lib.licenses.gpl3;
    maintainers = with lib.maintainers; [ osbm ];
    android = {
      minSdk = 26;
      targetSdk = 36;
      applicationId = "org.fossify.phone";
      versionCode = 22;
      abis = [
        "armeabi-v7a"
        "arm64-v8a"
        "x86"
        "x86_64"
      ];
    };
  };
}
