{
  pkgs,
  lib,
  ...
}:
lib.buildGradleApkGradle2Nix rec {
  pname = "aegis";
  version = "3.4.3";

  src = pkgs.applyPatches {
    name = "aegis-${version}-source";
    src = pkgs.fetchFromGitHub {
      owner = "beemdevelopment";
      repo = "Aegis";
      tag = "v${version}";
      hash = "sha256-qIcLruJsNMu4NQT0Wx3++0HbhMl/DD6C7VQKeCuVQUA=";
    };
    # The gradle.lock is generated from this patched source, so keep the
    # patching here rather than in the build derivation.
    postPatch = ''
      # upstream shells out to git at configuration time for BuildConfig
      # fields; there is no .git in the sandbox. Short hash of tag v${version},
      # branch as seen from a detached tag checkout.
      sed -i \
        -e 's|^def getGitHash = .*|def getGitHash = { -> return "d6f4e59" }|' \
        -e 's|^def getGitBranch = .*|def getGitBranch = { -> return "HEAD" }|' \
        app/build.gradle
      grep -q 'return "d6f4e59"' app/build.gradle
      grep -q 'return "HEAD"' app/build.gradle

      # the protobuf plugin downloads a prebuilt, dynamically linked protoc
      # from Maven Central, which cannot run in the sandbox. Use nixpkgs'
      # protoc from the same 3.25.x line instead.
      substituteInPlace app/build.gradle \
        --replace-fail \
          "artifact = 'com.google.protobuf:protoc:3.25.1'" \
          "path = '${pkgs.protobuf_25}/bin/protoc'"
    '';
  };

  androidSdkPackages =
    sdkPkgs: with sdkPkgs; [
      build-tools-35-0-0
      build-tools-36-0-0
      cmdline-tools-latest
      platform-tools
      platforms-android-36
    ];

  gradleTask = "assembleRelease";
  # per-app lock generated by the gradle2nix CLI (see docs/adding-new-app)
  lockFile = ./gradle.lock;
  apkPath = "app/build/outputs/apk/release/app-release-unsigned.apk";

  meta = {
    description = "Secure 2FA app for managing two-step verification tokens";
    homepage = "https://getaegis.app";
    license = lib.licenses.gpl3Only;
    maintainers = with lib.maintainers; [ osbm ];
    android = {
      minSdk = 23;
      targetSdk = 36;
      applicationId = "com.beemdevelopment.aegis";
      versionCode = 82;
      abis = [
        "armeabi-v7a"
        "arm64-v8a"
        "x86"
        "x86_64"
      ];
    };
  };
}
