name: "💡 App request"
description: Create a new ticket for a new app request
title: "💡 App request: <title>"
labels: [
  "type: app request"
]
body:
  - type: input
    id: source_url
    attributes:
      label: "Source URL (git, svn, etc)"
    validations:
      required: true
  - type: dropdown
    id: framework
    attributes:
      label: Select the framework
      multiple: false
      options:
        - Flutter
        - React Native
        - Gradle (kotlin or java)
        - Other
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: Provide any additional information that might be useful.
      placeholder: "issues, documentation, etc."
    validations:
      required: false
