{
  pkgs,
  lib,
  ...
}:
lib.buildGradleApkGradle2Nix {
  pname = "fossify-thankyou";
  version = "1.3.0";

  src = pkgs.fetchFromGitHub {
    owner = "FossifyOrg";
    repo = "Thank-You";
    tag = "1.3.0";
    hash = "sha256-FaXEPRYI6V/3clF3+xxx7PgoEXRmQZm4ESylpnKkM4s=";
  };

  androidSdkPackages =
    sdkPkgs: with sdkPkgs; [
      build-tools-35-0-0
      build-tools-36-0-0
      cmdline-tools-latest
      platform-tools
      platforms-android-36
    ];

  gradleTask = "assembleFossRelease";
  # per-app lock generated by the gradle2nix CLI (see docs/adding-new-app)
  lockFile = ./gradle.lock;
  apkPath = "app/build/outputs/apk/foss/release/thankyou-10-foss-release-unsigned.apk";

  meta = {
    description = "Community info app of the Fossify project, without ads";
    homepage = "https://fossify.org";
    license = lib.licenses.gpl3;
    maintainers = with lib.maintainers; [ osbm ];
    android = {
      minSdk = 26;
      targetSdk = 36;
      applicationId = "org.fossify.thankyou";
      versionCode = 10;
      abis = [
        "armeabi-v7a"
        "arm64-v8a"
        "x86"
        "x86_64"
      ];
    };
  };
}
