name: Build apps to test the derivations

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  push:

jobs:
  build-app:
    # use a matrix of (app, system, runner) so we build the appropriate
    # flake output for the runner OS. this runs 4 jobs: two apps x two systems.
    strategy:
      matrix:
        app-name: [smouldering_durtles, mihon]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Show flake outputs (debug)
        run: nix flake show

      - name: Build package
        run: |
          # build the system-specific package produced by the flake
          nix build -L ".#${{ matrix.app-name }}"
