name: Test Tailscale Build and Generate Dependencies

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test-tailscale-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Debug environment
        run: |
          echo "Working directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "Tailscale package files:"
          ls -la apks/ta/tailscale/
          echo "Current deps.json:"
          cat apks/ta/tailscale/deps.json

      - name: Build updateScript and run it
        run: |
          echo "Building mitmCache updateScript..."
          nix build -L '.#tailscale.mitmCache.updateScript'
          
          echo "Running updateScript to generate deps.json..."
          ./result
          
          echo "Checking if deps.json was updated:"
          ls -la apks/ta/tailscale/deps.json
          
      - name: Show generated deps.json content
        run: |
          echo "Generated deps.json content:"
          if [ -s apks/ta/tailscale/deps.json ]; then
            echo "File size: $(wc -c < apks/ta/tailscale/deps.json) bytes"
            head -50 apks/ta/tailscale/deps.json
          else
            echo "deps.json is empty or doesn't exist"
            cat apks/ta/tailscale/deps.json
          fi
          
      - name: Build Tailscale APK with populated deps.json
        run: |
          echo "Building Tailscale APK with populated dependencies..."
          nix build -L '.#tailscale'
          
          echo "Build successful! Checking output:"
          ls -la result*
