name: Test Tailscale Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test-tailscale-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Debug environment
        run: |
          echo "Working directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "Tailscale package files:"
          ls -la apks/ta/tailscale/
          echo "Current deps.json size:"
          wc -c apks/ta/tailscale/deps.json

      - name: Test Tailscale APK build
        run: |
          echo "Building Tailscale APK..."
          nix build -L '.#tailscale' --max-jobs 2
          
          echo "Build successful! Checking output:"
          ls -la result*
          
          if [ -f result ]; then
            echo "APK file details:"
            file result
            ls -lh result
          fi
